
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./data:/app/data
    # Если нужен доступ к .env, раскомментируйте следующую строку
    env_file:
      - .env
    # Если нужен проброс портов, раскомментируйте следующую строку
    # ports:
    #   - "8000:8000"